### ISSUE TITLE
Twilight Forest

### ISSUE THREAD

**Issue by penturt** [Darkhax-Minecraft/BotanyTrees#28] opened 2021-06-22 15:05 UTC
Support for plant/grow Twlight Forest related trees.

[Twilight Forest Mod](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)

**Comment by Darkhax** [comment] 2021-08-31 23:11
Thanks for the request. This is a duplicate of https://github.com/Darkhax-Minecraft/BotanyTrees/issues/26 so check there for updates on this.

**Closed as completed by Darkhax** 2021-08-31 23:11 UTC
Labels: duplicate
